# Jekyll configuration
markdown: kramdown
highlighter: rouge
language: 'en-us'

# Website info
cover: assets/images/blog-cover.jpg
logo: assets/images/logo.png
long_logo: assets/images/blog-icon.png
logo_dark: assets/images/logo-dark.png
favicon: assets/images/favicon.png
production_url: http://asteriskpound.com/
source_url: http://asteriskpound.com/

# Disqus
disqus: True
disqus_shortname: asteriskpound

# Site settings
title: Asterisk Pound
description: "*#!~ Oh the profanity"
#baseurl: "/" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol

# User settings
username: Alan Asher
user_description: Problem solver with a penchant for seeking out truth in the universe and creating my own with some friends.
user_title: "<img src='/assets/images/alien_avatar.png' class='codebender-icon'> The Last Codebender"
twitter_username: thezombiesplat
github_username:  zombiesplat
linkedin_username: thezombiesplat
stackoverflow_username: 1366872/zombiesplat

things_i_like: ['Dungeons & Dragons', 'Board Games', 'Drum Corps', 'Steam Punk', 'Conspiracy Theories', 'Leather Working', 'Solving Problems', 'Time Travel', 'Sleeping In on Saturdays']
dnd_characters: ['Thorin Von Sterlin : Dwarven Cleric : Lvl 6', 'Kaarl Deftkin : Human Rogue : Lvl 6', 'Nondo Aldebaran : Gray Mystic : Lvl 1', 'Lillith Gamwich : Halfling Oracle : Lvl 8', 'Ludwig Von Panzer : Human Eldritch Knight : Lvl 6', 'Echo Treefall : Firbolg Druid : Lvl 16']

titles: ['Scrum Master', 'Steve Irwin of Alient Hunters', 'Senior Web Application Engineer', 'Secretary of Sci-Fi', 'Guru of Geeks', 'Thinker of Things', 'Murder-Hobo Deluxe', 'Purveyor of Dad Jokes']
job_skills: ['PHP', 'Scrum', 'Javascript', 'VueJs', 'Laravel', 'AWS', 'CSS', 'HTML', 'SaaS', 'Linux', 'Git', 'jQuery']

super_powers: ['Convert Oxygen to Carbon Dioxide', 'Unable to Smell Skunk', '']
weaknesses: ['']

Accomplishments: ['']

# Google-analytics
google-analytics:
  id: "UA-113478195-1"

exclude: ['package.json', 'src', 'node_modules', '.idea']
