# Site settings
title: Asterisk Pound; not Star Hashtag
description: A description here
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Alan Asher
user_description: Problem solver with a penchant for seeking out truth in the universe and creating my own with some friends.
user_title: "Avatar <img src='/assets/img/alien_avatar.png' class='codebender-icon'> The Last Codebender"
twitter_username: zombiesplat1
github_username:  zombiesplat
linkedin_username: alan-asher-76aa7213a
stackoverflow_username: 1366872/zombiesplat

things_i_like: ['Dungeons & Dragons', 'Board Games', 'Drum Corps', 'Steam Punk', 'Conspiracy Theories', 'Leather Working', 'Solving Problems', 'Time Travel', 'Sleeping In on Saturdays']
dnd_characters: ['Thorin Von Sterlin : Dwarven Cleric : Lvl 6', 'Kaarl Deftkin : Human Rogue : Lvl 6', 'Nondo Aldebaran : Gray Mystic : Lvl 1', 'Lillith Gamwich : Halfling Oracle : Lvl 8', 'Ludwig Von Panzer : Human Eldritch Knight : Lvl 6', 'Echo Treefall : Firbolg Druid : Lvl 16']

titles: ['Scrum Master', 'Steve Irwin of Alient Hunters', 'Senior Web Application Engineer', 'Secretary of Sci-Fi', 'Guru of Geeks', 'Thinker of Things', 'Murder-Hobo Deluxe', 'Purveyor of Dad Jokes']
job_skills: ['PHP', 'Scrum', 'Javascript', 'VueJs', 'Laravel', 'AWS', 'CSS', 'HTML', 'SaaS', 'Linux', 'Git', 'jQuery']

super_powers: ['Convert Oxygen to Carbon Dioxide', 'Unable to Smell Skunk', '']
weaknesses: ['']

Accomplishments: ['']

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
